### ISSUE TITLE
Change vim.uv to vim.loop for stable

### ISSUE THREAD

**Issue by pcasotti** [dasupradyumna/launch.nvim#1]
After installing launch.nvim with lazy, i get the following error message on startup:

`.../.local/share/nvim/lazy/launch.nvim/plugin/launch.lua:31: attempt to index field 'uv' (a nil value)`

I believe that `vim.uv` is only available in 0.10 since i tested in 0.9.4, I suggest using `vim.loop` instead.

**Comment by dasupradyumna** [comment]
Ah, I'm sorry. Force of habit. I'll fix it up!
Thanks for pointing it out.
