### ISSUE TITLE
Is the launch.nvim plugin supported on Windows?

### ISSUE THREAD

**Issue by hungnguyen1503** [dasupradyumna/launch.nvim#4]
I have configured the task by using `LaunchOpenConfigFile` command and then I saved it, but I have a problem with the config path. It seems to duplicate the home config path. I also tried your plugin on Linux OS and it worked very well.
How to fix it on Windows?
![image](https://github.com/dasupradyumna/launch.nvim/assets/58872428/e2caadf7-2429-4c18-8983-011bddb4e579)
![image](https://github.com/dasupradyumna/launch.nvim/assets/58872428/27f10652-edcc-433c-bf2a-bf017f55d153)

**Comment by dasupradyumna** [comment]
I haven't yet tested the plugin on Windows. I will be doing so soon since I am currently busy giving job interviews.
Please give me one or two weeks! I'll get back to you :)

Cheers ~

**Comment by dasupradyumna** [comment]
I have started setting up a Windows port for my neovim.
Will start working on support for this plugin soon.

**Comment by dasupradyumna** [comment]
@hungnguyen1503 This was easier than I anticipated.
It should work on Windows as expected. Reopen if needed. :)

**Comment by hungnguyen1503** [comment]
Hi @dasupradyumna -san,

Your plugin has already worked very well on Windows. 💯 
Many thanks for your support. 👍🏻
