### ISSUE TITLE
Config not being loaded anymore as there is actual content in it

### ISSUE THREAD

**Issue by lukkigi** [dasupradyumna/launch.nvim#5]
Hey,

thanks for writing this plugin. Sadly I can't seem to actually add any tasks to it. Whenever I added anything to the task list, the config does not get loaded or refreshed anymore. If I leave the config completely empty, it shows the notification that the config has been reloaded, but it does not do that anymore with content in it. `LaunchShowTaskConfigs` also shows no tasks configured.

This is my minimal reproducible example:

```
 task = {
    {
      name = "List files",
      command = "ls -la"
    }
  }
}
```

**Comment by dasupradyumna** [comment]
Hey, that does not give me enough information to see what's wrong.
Can you elaborate the exact steps and commands to reproduce this?

**Comment by lukkigi** [comment]
I tried to make a small video showing the steps I did: https://www.youtube.com/watch?v=U_ROaiZhqE0

Notice how it shows the notification "User configurations loaded" for an empty file with just `return {}` but does not do so as soon as I created an actual task in the config

**Comment by dasupradyumna** [comment]
I noticed an "Autosave" notification in your video at 0:22 mark. Is that from a plugin or a built-in option?

Is that video captured with a minimal neovim configuration (i.e. only **launch** and its dependencies)??
If not, please try reproducing this behavior with a minimal config. That will help narrow down the source of the issue.

**Comment by dasupradyumna** [comment]
Closed due to lack of user feedback.
