### ISSUE TITLE
bug: the select user variable isn't selected

### ISSUE THREAD

**Issue by hungnguyen1503** [dasupradyumna/launch.nvim#7]
### Did you check documentation and existing issues?

- [X] I have read all the launch.nvim documentation
- [X] I have searched through all existing issues of launch.nvim
- [X] My issue is non-trivial and does not belong in the Discussions section

### Neovim Version (nvim -v)

0.10.0

### Operating System & Version

Win 10 

### Describe The Bug

Hi,

I have tried to use your example to test the user variable. 

### Steps To Reproduce

I realized that the select mode can't work, I have tried using it on both WinOS and Linux OS. 
```lua
return {
    task = {
        {
            name = 'Test User Variables',
            command = 'echo',
            args = { '{@select_type}', '{@input_type}' },
        }
    },
    var = {
        select_type = {
            type = 'select',
            desc = 'selection type variable',
            items = { '<item1>', '<item2>' }
        },
        input_type = {
            type = 'input',
            desc = 'input type variable',
            default = '<default_value>',
        },
    }
}
```

### Expected Behavior

Could you please support me to check it?

### Configuration Used To Reproduce

I used the default configuration which I follow your documentation

**Comment by dasupradyumna** [comment]
Hello, I am very sorry for the late response. I have been busy with my day-job.

I am currently using this plugin, and the select type variable works.
Are you still facing this bug? Could you please provide more details about the issue, with screenshots preferably?
That will help me understand it better. Thank you for your patience! ❤️

**Comment by dasupradyumna** [comment]
Feel free to re-open if needed.
